# Generated by Django 2.1 on 2018-08-24 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20180824_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2018), django.core.validators.MinValueValidator(1960)]),
        ),
    ]
